// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addAccount = `-- name: AddAccount :one
INSERT INTO accounts (id, created_at, updated_at, budget_id, account_type, name, notes, is_deleted)
VALUES (
    gen_random_uuid(),
    DEFAULT,
    DEFAULT,
    $1,
    $2,
    $3,
    $4,
    DEFAULT
)
RETURNING id, created_at, updated_at, budget_id, account_type, name, notes, is_deleted
`

type AddAccountParams struct {
	BudgetID    uuid.UUID
	AccountType string
	Name        string
	Notes       sql.NullString
}

func (q *Queries) AddAccount(ctx context.Context, arg AddAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, addAccount,
		arg.BudgetID,
		arg.AccountType,
		arg.Name,
		arg.Notes,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.AccountType,
		&i.Name,
		&i.Notes,
		&i.IsDeleted,
	)
	return i, err
}

const deleteAccountHard = `-- name: DeleteAccountHard :exec
DELETE
FROM accounts
WHERE accounts.id = $1
    AND accounts.is_deleted = TRUE
`

func (q *Queries) DeleteAccountHard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAccountHard, id)
	return err
}

const deleteAccountSoft = `-- name: DeleteAccountSoft :exec
UPDATE accounts
SET accounts.is_deleted = TRUE
WHERE accounts.id = $1
`

func (q *Queries) DeleteAccountSoft(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAccountSoft, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, created_at, updated_at, budget_id, account_type, name, notes, is_deleted
FROM accounts
WHERE accounts.id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.AccountType,
		&i.Name,
		&i.Notes,
		&i.IsDeleted,
	)
	return i, err
}

const getAccountsFromBudget = `-- name: GetAccountsFromBudget :many
SELECT id, created_at, updated_at, budget_id, account_type, name, notes, is_deleted
FROM accounts
WHERE accounts.budget_id = $1
`

func (q *Queries) GetAccountsFromBudget(ctx context.Context, budgetID uuid.UUID) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAccountsFromBudget, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BudgetID,
			&i.AccountType,
			&i.Name,
			&i.Notes,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBudgetAccountCapital = `-- name: GetBudgetAccountCapital :one
SELECT CAST(COALESCE(SUM(transactions_view.total_amount), 0) AS BIGINT) AS total
FROM transactions_view
WHERE transactions_view.account_id = $1
`

func (q *Queries) GetBudgetAccountCapital(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBudgetAccountCapital, accountID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const restoreAccount = `-- name: RestoreAccount :exec
UPDATE accounts
SET accounts.is_deleted = FALSE
WHERE accounts.id = $1
`

func (q *Queries) RestoreAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, restoreAccount, id)
	return err
}
