// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: assignment.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignAmountToCategory = `-- name: AssignAmountToCategory :one
INSERT INTO assignments (month, category_id, assigned)
VALUES (
  DATE_TRUNC('month', $1::timestamp),
  $2,
  $3
)
ON CONFLICT (month, category_id)
DO UPDATE
SET assigned = assignments.assigned + EXCLUDED.assigned
RETURNING month, category_id, assigned
`

type AssignAmountToCategoryParams struct {
	MonthID    time.Time
	CategoryID uuid.UUID
	Amount     int64
}

func (q *Queries) AssignAmountToCategory(ctx context.Context, arg AssignAmountToCategoryParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, assignAmountToCategory, arg.MonthID, arg.CategoryID, arg.Amount)
	var i Assignment
	err := row.Scan(&i.Month, &i.CategoryID, &i.Assigned)
	return i, err
}

const deleteMonthAssignmentForCat = `-- name: DeleteMonthAssignmentForCat :exec
DELETE FROM assignments
WHERE $1 = month AND $2 = category_id
`

type DeleteMonthAssignmentForCatParams struct {
	Month      time.Time
	CategoryID uuid.UUID
}

func (q *Queries) DeleteMonthAssignmentForCat(ctx context.Context, arg DeleteMonthAssignmentForCatParams) error {
	_, err := q.db.Exec(ctx, deleteMonthAssignmentForCat, arg.Month, arg.CategoryID)
	return err
}
