// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignment.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignAmountToCategory = `-- name: AssignAmountToCategory :one
INSERT INTO assignments (month, category_id, assigned)
VALUES (
  DATE_TRUNC('month', $1::timestamp),
  $2,
  $3
)
ON CONFLICT (month, category_id)
DO UPDATE
SET assigned = assignments.assigned + EXCLUDED.assigned
RETURNING month, category_id, assigned
`

type AssignAmountToCategoryParams struct {
	MonthID    time.Time
	CategoryID uuid.UUID
	Amount     int64
}

func (q *Queries) AssignAmountToCategory(ctx context.Context, arg AssignAmountToCategoryParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, assignAmountToCategory, arg.MonthID, arg.CategoryID, arg.Amount)
	var i Assignment
	err := row.Scan(&i.Month, &i.CategoryID, &i.Assigned)
	return i, err
}

const deleteMonthAssignmentForCat = `-- name: DeleteMonthAssignmentForCat :exec
DELETE FROM assignments
WHERE $1 = month AND $2 = category_id
`

type DeleteMonthAssignmentForCatParams struct {
	Month      time.Time
	CategoryID uuid.UUID
}

func (q *Queries) DeleteMonthAssignmentForCat(ctx context.Context, arg DeleteMonthAssignmentForCatParams) error {
	_, err := q.db.ExecContext(ctx, deleteMonthAssignmentForCat, arg.Month, arg.CategoryID)
	return err
}

const getMonthCategoryReport = `-- name: GetMonthCategoryReport :one
SELECT month, category_name, category_id, assigned, activity, balance FROM category_reports cr
WHERE cr.month = $1 AND cr.category_id = $2
`

type GetMonthCategoryReportParams struct {
	Month      time.Time
	CategoryID uuid.UUID
}

func (q *Queries) GetMonthCategoryReport(ctx context.Context, arg GetMonthCategoryReportParams) (CategoryReport, error) {
	row := q.db.QueryRowContext(ctx, getMonthCategoryReport, arg.Month, arg.CategoryID)
	var i CategoryReport
	err := row.Scan(
		&i.Month,
		&i.CategoryName,
		&i.CategoryID,
		&i.Assigned,
		&i.Activity,
		&i.Balance,
	)
	return i, err
}

const getMonthCategoryReports = `-- name: GetMonthCategoryReports :many
SELECT month, category_name, category_id, assigned, activity, balance FROM category_reports cr
WHERE cr.month = $1
`

func (q *Queries) GetMonthCategoryReports(ctx context.Context, month time.Time) ([]CategoryReport, error) {
	rows, err := q.db.QueryContext(ctx, getMonthCategoryReports, month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryReport
	for rows.Next() {
		var i CategoryReport
		if err := rows.Scan(
			&i.Month,
			&i.CategoryName,
			&i.CategoryID,
			&i.Assigned,
			&i.Activity,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthReport = `-- name: GetMonthReport :one
SELECT
    COALESCE(SUM(assigned), 0)::bigint AS assigned,
    COALESCE(SUM(activity), 0)::bigint AS activity,
    COALESCE(SUM(balance), 0)::bigint AS balance
FROM category_reports mr
WHERE mr.month = $1
`

type GetMonthReportRow struct {
	Assigned int64
	Activity int64
	Balance  int64
}

func (q *Queries) GetMonthReport(ctx context.Context, month time.Time) (GetMonthReportRow, error) {
	row := q.db.QueryRowContext(ctx, getMonthReport, month)
	var i GetMonthReportRow
	err := row.Scan(&i.Assigned, &i.Activity, &i.Balance)
	return i, err
}
