// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: assignment.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignAmountToCategory = `-- name: AssignAmountToCategory :one
INSERT INTO assignments (month, category_id, assigned)
VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (month, category_id)
DO UPDATE
SET assigned = assignments.assigned + EXCLUDED.assigned
RETURNING month, category_id, assigned
`

type AssignAmountToCategoryParams struct {
	MonthID    time.Time
	CategoryID uuid.UUID
	Assigned   int64
}

func (q *Queries) AssignAmountToCategory(ctx context.Context, arg AssignAmountToCategoryParams) (Assignment, error) {
	row := q.db.QueryRowContext(ctx, assignAmountToCategory, arg.MonthID, arg.CategoryID, arg.Assigned)
	var i Assignment
	err := row.Scan(&i.Month, &i.CategoryID, &i.Assigned)
	return i, err
}

const deleteMonthAssignmentForCat = `-- name: DeleteMonthAssignmentForCat :exec
DELETE FROM assignments
WHERE $1 = assignments.month AND $2 = assignments.category_id
`

type DeleteMonthAssignmentForCatParams struct {
	Month      time.Time
	CategoryID uuid.UUID
}

func (q *Queries) DeleteMonthAssignmentForCat(ctx context.Context, arg DeleteMonthAssignmentForCatParams) error {
	_, err := q.db.ExecContext(ctx, deleteMonthAssignmentForCat, arg.Month, arg.CategoryID)
	return err
}

const getMonthCategory = `-- name: GetMonthCategory :one
SELECT month, name, assigned, category_id, activity, balance FROM month_report ar
WHERE ar.month = $1 AND ar.category_id = $2
`

type GetMonthCategoryParams struct {
	Month      time.Time
	CategoryID uuid.UUID
}

func (q *Queries) GetMonthCategory(ctx context.Context, arg GetMonthCategoryParams) (MonthReport, error) {
	row := q.db.QueryRowContext(ctx, getMonthCategory, arg.Month, arg.CategoryID)
	var i MonthReport
	err := row.Scan(
		&i.Month,
		&i.Name,
		&i.Assigned,
		&i.CategoryID,
		&i.Activity,
		&i.Balance,
	)
	return i, err
}

const getMonthReport = `-- name: GetMonthReport :many
SELECT month, name, assigned, category_id, activity, balance FROM month_report ar
WHERE ar.month = $1
`

func (q *Queries) GetMonthReport(ctx context.Context, month time.Time) ([]MonthReport, error) {
	rows, err := q.db.QueryContext(ctx, getMonthReport, month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthReport
	for rows.Next() {
		var i MonthReport
		if err := rows.Scan(
			&i.Month,
			&i.Name,
			&i.Assigned,
			&i.CategoryID,
			&i.Activity,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
