// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const assignBudgetMemberWithRole = `-- name: AssignBudgetMemberWithRole :one
INSERT INTO budgets_users (created_at, updated_at, budget_id, user_id, member_role)
VALUES (
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
ON CONFLICT (budget_id, user_id) DO UPDATE
SET updated_at = EXCLUDED.updated_at, member_role = EXCLUDED.member_role
RETURNING created_at, updated_at, budget_id, user_id, member_role
`

type AssignBudgetMemberWithRoleParams struct {
	BudgetID   uuid.UUID
	UserID     uuid.UUID
	MemberRole string
}

func (q *Queries) AssignBudgetMemberWithRole(ctx context.Context, arg AssignBudgetMemberWithRoleParams) (BudgetsUser, error) {
	row := q.db.QueryRowContext(ctx, assignBudgetMemberWithRole, arg.BudgetID, arg.UserID, arg.MemberRole)
	var i BudgetsUser
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.UserID,
		&i.MemberRole,
	)
	return i, err
}

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (id, created_at, updated_at, admin_id, name, notes)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, admin_id, name, notes
`

type CreateBudgetParams struct {
	AdminID uuid.UUID
	Name    string
	Notes   string
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, createBudget, arg.AdminID, arg.Name, arg.Notes)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdminID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE
FROM budgets
WHERE id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBudget, id)
	return err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, created_at, updated_at, admin_id, name, notes
FROM budgets
WHERE id = $1
`

func (q *Queries) GetBudgetByID(ctx context.Context, id uuid.UUID) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudgetByID, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdminID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const getBudgetCapital = `-- name: GetBudgetCapital :one
SELECT CAST(COALESCE(SUM(transactions_view.total_amount), 0) AS BIGINT) AS total
FROM transactions_view
WHERE transactions_view.budget_id = $1
`

func (q *Queries) GetBudgetCapital(ctx context.Context, budgetID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBudgetCapital, budgetID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getBudgetMemberRole = `-- name: GetBudgetMemberRole :one
SELECT member_role
FROM budgets_users
WHERE budget_id = $1 AND user_id = $2
`

type GetBudgetMemberRoleParams struct {
	BudgetID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetBudgetMemberRole(ctx context.Context, arg GetBudgetMemberRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getBudgetMemberRole, arg.BudgetID, arg.UserID)
	var member_role string
	err := row.Scan(&member_role)
	return member_role, err
}

const getUserBudgets = `-- name: GetUserBudgets :many
(
  SELECT budgets.id, budgets.created_at, budgets.updated_at, budgets.admin_id, budgets.name, budgets.notes
  FROM budgets
  JOIN budgets_users
    ON budgets.id = budgets_users.budget_id
  WHERE budgets_users.user_id = $1
    AND ($2::text[] IS NULL OR budgets_users.member_role = ANY($2::text[]))
)
UNION
(
  SELECT budgets.id, budgets.created_at, budgets.updated_at, budgets.admin_id, budgets.name, budgets.notes
  FROM budgets
  WHERE admin_id = $1
)
`

type GetUserBudgetsParams struct {
	UserID uuid.UUID
	Roles  []string
}

func (q *Queries) GetUserBudgets(ctx context.Context, arg GetUserBudgetsParams) ([]Budget, error) {
	rows, err := q.db.QueryContext(ctx, getUserBudgets, arg.UserID, pq.Array(arg.Roles))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AdminID,
			&i.Name,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeBudgetMembership = `-- name: RevokeBudgetMembership :exec
DELETE
FROM budgets_users
WHERE budget_id = $1
    AND user_id = $2
`

type RevokeBudgetMembershipParams struct {
	BudgetID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) RevokeBudgetMembership(ctx context.Context, arg RevokeBudgetMembershipParams) error {
	_, err := q.db.ExecContext(ctx, revokeBudgetMembership, arg.BudgetID, arg.UserID)
	return err
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets
SET updated_at = NOW(), name = $2, notes = $3
WHERE id = $1
RETURNING id, created_at, updated_at, admin_id, name, notes
`

type UpdateBudgetParams struct {
	ID    uuid.UUID
	Name  string
	Notes string
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, updateBudget, arg.ID, arg.Name, arg.Notes)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdminID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}
