// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: budgets.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const assignBudgetMemberWithRole = `-- name: AssignBudgetMemberWithRole :one
INSERT INTO budgets_users (created_at, updated_at, budget_id, user_id, member_role)
VALUES (
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
ON CONFLICT (budget_id, user_id) DO UPDATE
SET updated_at = EXCLUDED.updated_at, member_role = EXCLUDED.member_role
RETURNING created_at, updated_at, budget_id, user_id, member_role
`

type AssignBudgetMemberWithRoleParams struct {
	BudgetID   uuid.UUID
	UserID     uuid.UUID
	MemberRole string
}

func (q *Queries) AssignBudgetMemberWithRole(ctx context.Context, arg AssignBudgetMemberWithRoleParams) (BudgetsUser, error) {
	row := q.db.QueryRow(ctx, assignBudgetMemberWithRole, arg.BudgetID, arg.UserID, arg.MemberRole)
	var i BudgetsUser
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.UserID,
		&i.MemberRole,
	)
	return i, err
}

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (id, created_at, updated_at, admin_id, name, notes)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, admin_id, name, notes
`

type CreateBudgetParams struct {
	AdminID uuid.UUID
	Name    string
	Notes   string
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget, arg.AdminID, arg.Name, arg.Notes)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdminID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE
FROM budgets
WHERE id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBudget, id)
	return err
}

const getBudgetAccountIDAndTypeByName = `-- name: GetBudgetAccountIDAndTypeByName :one
SELECT id, account_type
FROM accounts
WHERE name = $1
AND budget_id = $2
`

type GetBudgetAccountIDAndTypeByNameParams struct {
	AccountName string
	BudgetID    uuid.UUID
}

type GetBudgetAccountIDAndTypeByNameRow struct {
	ID          uuid.UUID
	AccountType string
}

func (q *Queries) GetBudgetAccountIDAndTypeByName(ctx context.Context, arg GetBudgetAccountIDAndTypeByNameParams) (GetBudgetAccountIDAndTypeByNameRow, error) {
	row := q.db.QueryRow(ctx, getBudgetAccountIDAndTypeByName, arg.AccountName, arg.BudgetID)
	var i GetBudgetAccountIDAndTypeByNameRow
	err := row.Scan(&i.ID, &i.AccountType)
	return i, err
}

const getBudgetAccountIDByName = `-- name: GetBudgetAccountIDByName :one

SELECT id
FROM accounts
WHERE name = $1
AND budget_id = $2
`

type GetBudgetAccountIDByNameParams struct {
	AccountName string
	BudgetID    uuid.UUID
}

// RESOURCE ID RETRIEVAL
func (q *Queries) GetBudgetAccountIDByName(ctx context.Context, arg GetBudgetAccountIDByNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getBudgetAccountIDByName, arg.AccountName, arg.BudgetID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, created_at, updated_at, admin_id, name, notes
FROM budgets
WHERE id = $1
`

func (q *Queries) GetBudgetByID(ctx context.Context, id uuid.UUID) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdminID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const getBudgetCapital = `-- name: GetBudgetCapital :one
SELECT CAST(COALESCE(SUM(td.total_amount), 0) AS BIGINT) AS total
FROM transaction_details td
JOIN transactions t ON td.id = t.id
JOIN accounts a ON t.account_id = a.id
WHERE t.budget_id = $1
  AND $2::text = ''
  OR a.account_type = $2
`

type GetBudgetCapitalParams struct {
	BudgetID    uuid.UUID
	AccountType string
}

func (q *Queries) GetBudgetCapital(ctx context.Context, arg GetBudgetCapitalParams) (int64, error) {
	row := q.db.QueryRow(ctx, getBudgetCapital, arg.BudgetID, arg.AccountType)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getBudgetCategoryIDByName = `-- name: GetBudgetCategoryIDByName :one
SELECT id
FROM categories
WHERE name = $1
AND budget_id = $2
`

type GetBudgetCategoryIDByNameParams struct {
	CategoryName string
	BudgetID     uuid.UUID
}

func (q *Queries) GetBudgetCategoryIDByName(ctx context.Context, arg GetBudgetCategoryIDByNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getBudgetCategoryIDByName, arg.CategoryName, arg.BudgetID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getBudgetGroupIDByName = `-- name: GetBudgetGroupIDByName :one
SELECT id
FROM groups
WHERE name = $1
AND budget_id = $2
`

type GetBudgetGroupIDByNameParams struct {
	GroupName string
	BudgetID  uuid.UUID
}

func (q *Queries) GetBudgetGroupIDByName(ctx context.Context, arg GetBudgetGroupIDByNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getBudgetGroupIDByName, arg.GroupName, arg.BudgetID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getBudgetMemberRole = `-- name: GetBudgetMemberRole :one
SELECT member_role
FROM budgets_users
WHERE budget_id = $1 AND user_id = $2
`

type GetBudgetMemberRoleParams struct {
	BudgetID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetBudgetMemberRole(ctx context.Context, arg GetBudgetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getBudgetMemberRole, arg.BudgetID, arg.UserID)
	var member_role string
	err := row.Scan(&member_role)
	return member_role, err
}

const getBudgetPayeeIDByName = `-- name: GetBudgetPayeeIDByName :one
SELECT id
FROM payees
WHERE name = $1
AND budget_id = $2
`

type GetBudgetPayeeIDByNameParams struct {
	PayeeName string
	BudgetID  uuid.UUID
}

func (q *Queries) GetBudgetPayeeIDByName(ctx context.Context, arg GetBudgetPayeeIDByNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getBudgetPayeeIDByName, arg.PayeeName, arg.BudgetID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserBudgets = `-- name: GetUserBudgets :many
SELECT budgets.id, budgets.created_at, budgets.updated_at, budgets.admin_id, budgets.name, budgets.notes
FROM budgets
JOIN budgets_users
  ON budgets.id = budgets_users.budget_id
WHERE budgets_users.user_id = $1
  AND (
    $2::text[] IS NULL
    OR cardinality($2::text[]) = 0
    OR budgets_users.member_role = ANY($2::text[])
  )
`

type GetUserBudgetsParams struct {
	UserID uuid.UUID
	Roles  []string
}

func (q *Queries) GetUserBudgets(ctx context.Context, arg GetUserBudgetsParams) ([]Budget, error) {
	rows, err := q.db.Query(ctx, getUserBudgets, arg.UserID, arg.Roles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AdminID,
			&i.Name,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeBudgetMembership = `-- name: RevokeBudgetMembership :exec
DELETE
FROM budgets_users
WHERE budget_id = $1
    AND user_id = $2
`

type RevokeBudgetMembershipParams struct {
	BudgetID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) RevokeBudgetMembership(ctx context.Context, arg RevokeBudgetMembershipParams) error {
	_, err := q.db.Exec(ctx, revokeBudgetMembership, arg.BudgetID, arg.UserID)
	return err
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets
SET updated_at = NOW(), name = $2, notes = $3
WHERE id = $1
RETURNING id, created_at, updated_at, admin_id, name, notes
`

type UpdateBudgetParams struct {
	ID    uuid.UUID
	Name  string
	Notes string
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget, arg.ID, arg.Name, arg.Notes)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AdminID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}
