// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: budgets.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const assignBudgetUserWithRole = `-- name: AssignBudgetUserWithRole :one
INSERT INTO budgets_users (created_at, updated_at, budget_id, user_id, user_role)
VALUES (
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
ON CONFLICT (budget_id, user_id) DO UPDATE
SET updated_at = EXCLUDED.updated_at, user_role = EXCLUDED.user_role
RETURNING created_at, updated_at, budget_id, user_id, user_role
`

type AssignBudgetUserWithRoleParams struct {
	BudgetID uuid.UUID
	UserID   uuid.UUID
	UserRole string
}

func (q *Queries) AssignBudgetUserWithRole(ctx context.Context, arg AssignBudgetUserWithRoleParams) (BudgetsUser, error) {
	row := q.db.QueryRowContext(ctx, assignBudgetUserWithRole, arg.BudgetID, arg.UserID, arg.UserRole)
	var i BudgetsUser
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.UserID,
		&i.UserRole,
	)
	return i, err
}

const assignCategoryToGroup = `-- name: AssignCategoryToGroup :one
UPDATE categories
SET updated_at = NOW(), group_id = $2
WHERE id = $1
RETURNING id, created_at, updated_at, user_id, name, group_id, notes
`

type AssignCategoryToGroupParams struct {
	ID      uuid.UUID
	GroupID uuid.NullUUID
}

func (q *Queries) AssignCategoryToGroup(ctx context.Context, arg AssignCategoryToGroupParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, assignCategoryToGroup, arg.ID, arg.GroupID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
		&i.GroupID,
		&i.Notes,
	)
	return i, err
}

const createBudget = `-- name: CreateBudget :one

INSERT INTO budgets (id, created_at, updated_at, name, notes)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, name, notes
`

type CreateBudgetParams struct {
	Name  string
	Notes sql.NullString
}

// BUDGET CRUD
func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, createBudget, arg.Name, arg.Notes)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO categories (id, created_at, updated_at, user_id, group_id, name, notes)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, created_at, updated_at, user_id, name, group_id, notes
`

type CreateCategoryParams struct {
	UserID  uuid.UUID
	GroupID uuid.NullUUID
	Name    string
	Notes   string
}

// CATEGORY CRUD
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.UserID,
		arg.GroupID,
		arg.Name,
		arg.Notes,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
		&i.GroupID,
		&i.Notes,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one

INSERT INTO groups (id, created_at, updated_at, user_id, name, notes)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, user_id, name, notes
`

type CreateGroupParams struct {
	UserID uuid.UUID
	Name   string
	Notes  string
}

// GROUP CRUD
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.UserID, arg.Name, arg.Notes)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE
FROM budgets
WHERE budgets.id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBudget, id)
	return err
}

const deleteCategoryByID = `-- name: DeleteCategoryByID :exec
DELETE
FROM categories
WHERE categories.id = $1
`

func (q *Queries) DeleteCategoryByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategoryByID, id)
	return err
}

const deleteGroupByID = `-- name: DeleteGroupByID :exec
DELETE
FROM groups
WHERE groups.id = $1
`

func (q *Queries) DeleteGroupByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroupByID, id)
	return err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, created_at, updated_at, name, notes
FROM budgets
WHERE budgets.id = $1
`

func (q *Queries) GetBudgetByID(ctx context.Context, id uuid.UUID) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudgetByID, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const getCategoriesByGroup = `-- name: GetCategoriesByGroup :many
SELECT id, created_at, updated_at, user_id, name, group_id, notes
FROM categories
WHERE categories.group_id = $1
`

func (q *Queries) GetCategoriesByGroup(ctx context.Context, groupID uuid.NullUUID) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Name,
			&i.GroupID,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesByUserID = `-- name: GetCategoriesByUserID :many
SELECT id, created_at, updated_at, user_id, name, group_id, notes
FROM categories
WHERE categories.user_id = $1
`

func (q *Queries) GetCategoriesByUserID(ctx context.Context, userID uuid.UUID) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Name,
			&i.GroupID,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, created_at, updated_at, user_id, name, group_id, notes
FROM categories
WHERE categories.id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
		&i.GroupID,
		&i.Notes,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, created_at, updated_at, user_id, name, notes
FROM groups
WHERE groups.id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const getGroupByUserIDAndName = `-- name: GetGroupByUserIDAndName :one
SELECT id, created_at, updated_at, user_id, name, notes
FROM groups
WHERE groups.name = $1 AND groups.user_id = $2
`

type GetGroupByUserIDAndNameParams struct {
	Name   string
	UserID uuid.UUID
}

func (q *Queries) GetGroupByUserIDAndName(ctx context.Context, arg GetGroupByUserIDAndNameParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByUserIDAndName, arg.Name, arg.UserID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const getGroupsByUserID = `-- name: GetGroupsByUserID :many
SELECT id, created_at, updated_at, user_id, name, notes
FROM groups
WHERE groups.user_id = $1
`

func (q *Queries) GetGroupsByUserID(ctx context.Context, userID uuid.UUID) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Name,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBudgets = `-- name: GetUserBudgets :many
SELECT budgets.id, budgets.created_at, budgets.updated_at, budgets.name, budgets.notes, budgets_users.user_role
FROM budgets
JOIN budgets_users
ON budgets.id = budgets_users.budget_id
WHERE budgets_users.user_id = $1
`

type GetUserBudgetsRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Notes     sql.NullString
	UserRole  string
}

func (q *Queries) GetUserBudgets(ctx context.Context, userID uuid.UUID) ([]GetUserBudgetsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserBudgets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserBudgetsRow
	for rows.Next() {
		var i GetUserBudgetsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Notes,
			&i.UserRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
