// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, created_at, updated_at, budget_id, group_id, name, notes)
VALUES (
    gen_random_uuid(),
    DEFAULT,
    DEFAULT,
    $1,
    $2,
    $3,
    $4
)
RETURNING id, created_at, updated_at, budget_id, name, group_id, notes
`

type CreateCategoryParams struct {
	BudgetID uuid.UUID
	GroupID  uuid.NullUUID
	Name     string
	Notes    string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.BudgetID,
		arg.GroupID,
		arg.Name,
		arg.Notes,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.Name,
		&i.GroupID,
		&i.Notes,
	)
	return i, err
}

const deleteCategoryByID = `-- name: DeleteCategoryByID :exec
DELETE
FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategoryByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategoryByID, id)
	return err
}

const getCategories = `-- name: GetCategories :many
SELECT id, created_at, updated_at, budget_id, name, group_id, notes
FROM categories c
WHERE c.budget_id = $1
  AND ( -- TODO: Lesson learned. Separate stuff like this into separate queries! This is just messy.
    $2::uuid = '00000000-0000-0000-0000-000000000000'
    OR c.group_id = $2::uuid
  )
`

type GetCategoriesParams struct {
	BudgetID uuid.UUID
	GroupID  uuid.UUID
}

func (q *Queries) GetCategories(ctx context.Context, arg GetCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategories, arg.BudgetID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BudgetID,
			&i.Name,
			&i.GroupID,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, created_at, updated_at, budget_id, name, group_id, notes
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.Name,
		&i.GroupID,
		&i.Notes,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET updated_at = NOW(), group_id = $2, name = $3, notes = $4
WHERE id = $1
RETURNING id, created_at, updated_at, budget_id, name, group_id, notes
`

type UpdateCategoryParams struct {
	ID      uuid.UUID
	GroupID uuid.NullUUID
	Name    string
	Notes   string
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.GroupID,
		arg.Name,
		arg.Notes,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.Name,
		&i.GroupID,
		&i.Notes,
	)
	return i, err
}
