// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one

INSERT INTO groups (id, created_at, updated_at, budget_id, name, notes)
VALUES (
    gen_random_uuid(),
    DEFAULT,
    DEFAULT,
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, budget_id, name, notes
`

type CreateGroupParams struct {
	BudgetID uuid.UUID
	Name     string
	Notes    string
}

// GROUP CRUD
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.BudgetID, arg.Name, arg.Notes)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const deleteGroupByID = `-- name: DeleteGroupByID :exec
DELETE
FROM groups
WHERE id = $1
`

func (q *Queries) DeleteGroupByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroupByID, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, created_at, updated_at, budget_id, name, notes
FROM groups
WHERE budget_id = $1
    AND id = $2
`

type GetGroupByIDParams struct {
	BudgetID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetGroupByID(ctx context.Context, arg GetGroupByIDParams) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, arg.BudgetID, arg.ID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const getGroupsByBudgetID = `-- name: GetGroupsByBudgetID :many
SELECT id, created_at, updated_at, budget_id, name, notes
FROM groups
WHERE budget_id = $1
`

func (q *Queries) GetGroupsByBudgetID(ctx context.Context, budgetID uuid.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, getGroupsByBudgetID, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BudgetID,
			&i.Name,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET updated_at = NOW(), name = $2, notes = $3
WHERE id = $1
RETURNING id, created_at, updated_at, budget_id, name, notes
`

type UpdateGroupParams struct {
	ID    uuid.UUID
	Name  string
	Notes string
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.ID, arg.Name, arg.Notes)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}
