// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	BudgetID    uuid.UUID
	AccountType string
	Name        string
	Notes       sql.NullString
	IsDeleted   bool
}

type AccountTransfer struct {
	ID                uuid.UUID
	FromTransactionID uuid.UUID
	ToTransactionID   uuid.UUID
}

type Budget struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	AdminID   uuid.UUID
	Name      string
	Notes     sql.NullString
}

type BudgetsUser struct {
	CreatedAt  time.Time
	UpdatedAt  time.Time
	BudgetID   uuid.UUID
	UserID     uuid.UUID
	MemberRole string
}

type Category struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	BudgetID  uuid.UUID
	Name      string
	GroupID   uuid.NullUUID
	Notes     string
}

type Group struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	BudgetID  uuid.UUID
	Name      string
	Notes     string
}

type Payee struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	BudgetID  uuid.UUID
	Name      string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Transaction struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	BudgetID        uuid.UUID
	LoggerID        uuid.UUID
	AccountID       uuid.UUID
	TransactionType string
	TransactionDate time.Time
	PayeeID         uuid.UUID
	Notes           string
	Cleared         bool
}

type TransactionSplit struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	CategoryID    uuid.NullUUID
	Amount        int64
}

type TransactionsView struct {
	ID              uuid.UUID
	TransactionType string
	TransactionDate time.Time
	Payee           string
	PayeeID         uuid.UUID
	Notes           string
	BudgetID        uuid.UUID
	AccountID       uuid.UUID
	LoggerID        uuid.UUID
	TotalAmount     int64
	Splits          json.RawMessage
	Cleared         bool
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Username       string
	HashedPassword string
}
