// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	BudgetID    uuid.UUID
	AccountType string
	Name        string
	Description sql.NullString
}

type Budget struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	AdminID   uuid.UUID
	Name      string
	Notes     sql.NullString
}

type BudgetsUser struct {
	CreatedAt  time.Time
	UpdatedAt  time.Time
	BudgetID   uuid.UUID
	UserID     uuid.UUID
	MemberRole string
}

type Category struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	BudgetID  uuid.UUID
	Name      string
	GroupID   uuid.NullUUID
	Notes     string
}

type Group struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	BudgetID  uuid.UUID
	Name      string
	Notes     string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Transaction struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
	BudgetID    uuid.UUID
	AccountID   uuid.UUID
	Datetime    time.Time
	Payees      string
	Notes       string
	Amount      sql.NullInt32
	SplitAmount string
	Cleared     bool
}

type TransactionCategory struct {
	TransactionID uuid.UUID
	CategoryID    uuid.UUID
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Username       string
	HashedPassword string
}
