// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payees.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPayee = `-- name: CreatePayee :one
INSERT INTO payees (id, created_at, updated_at, budget_id, name, notes)
VALUES (
    gen_random_uuid(),
    DEFAULT,
    DEFAULT,
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, budget_id, name, notes
`

type CreatePayeeParams struct {
	BudgetID uuid.UUID
	Name     string
	Notes    string
}

func (q *Queries) CreatePayee(ctx context.Context, arg CreatePayeeParams) (Payee, error) {
	row := q.db.QueryRowContext(ctx, createPayee, arg.BudgetID, arg.Name, arg.Notes)
	var i Payee
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const deletePayee = `-- name: DeletePayee :exec
DELETE
FROM payees
WHERE payees.id = $1
`

func (q *Queries) DeletePayee(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePayee, id)
	return err
}

const getBudgetPayees = `-- name: GetBudgetPayees :many
SELECT id, created_at, updated_at, budget_id, name, notes
FROM payees
WHERE payees.budget_id = $1
`

func (q *Queries) GetBudgetPayees(ctx context.Context, budgetID uuid.UUID) ([]Payee, error) {
	rows, err := q.db.QueryContext(ctx, getBudgetPayees, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payee
	for rows.Next() {
		var i Payee
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BudgetID,
			&i.Name,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPayeeByID = `-- name: GetPayeeByID :one
SELECT id, created_at, updated_at, budget_id, name, notes
FROM payees
WHERE payees.id = $1
`

func (q *Queries) GetPayeeByID(ctx context.Context, id uuid.UUID) (Payee, error) {
	row := q.db.QueryRowContext(ctx, getPayeeByID, id)
	var i Payee
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}

const updatePayee = `-- name: UpdatePayee :one
UPDATE payees
SET updated_at = NOW(), name = $2, notes = $3
WHERE id = $1
RETURNING id, created_at, updated_at, budget_id, name, notes
`

type UpdatePayeeParams struct {
	ID    uuid.UUID
	Name  string
	Notes string
}

func (q *Queries) UpdatePayee(ctx context.Context, arg UpdatePayeeParams) (Payee, error) {
	row := q.db.QueryRowContext(ctx, updatePayee, arg.ID, arg.Name, arg.Notes)
	var i Payee
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.Name,
		&i.Notes,
	)
	return i, err
}
