// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: reporting.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getMonthCategoryReport = `-- name: GetMonthCategoryReport :one
SELECT 
  month::DATE AS month,
  category_id::uuid AS category_id,
  category_name::text AS category_name,
  COALESCE(assigned, 0)::bigint AS assigned,
  COALESCE(activity, 0)::bigint AS activity,
  COALESCE(balance, 0)::bigint AS balance
FROM rep.get_category_reports_gate(
  $1::uuid, 
  $2::date
)
WHERE category_id = $3::uuid
LIMIT 1
`

type GetMonthCategoryReportParams struct {
	BudgetID   uuid.UUID
	MonthID    time.Time
	CategoryID uuid.UUID
}

type GetMonthCategoryReportRow struct {
	Month        time.Time
	CategoryID   uuid.UUID
	CategoryName string
	Assigned     int64
	Activity     int64
	Balance      int64
}

func (q *Queries) GetMonthCategoryReport(ctx context.Context, arg GetMonthCategoryReportParams) (GetMonthCategoryReportRow, error) {
	row := q.db.QueryRow(ctx, getMonthCategoryReport, arg.BudgetID, arg.MonthID, arg.CategoryID)
	var i GetMonthCategoryReportRow
	err := row.Scan(
		&i.Month,
		&i.CategoryID,
		&i.CategoryName,
		&i.Assigned,
		&i.Activity,
		&i.Balance,
	)
	return i, err
}

const getMonthCategoryReports = `-- name: GetMonthCategoryReports :many
SELECT 
  month::DATE AS month,
  category_id::uuid AS category_id,
  category_name::text AS category_name,
  COALESCE(assigned, 0)::bigint AS assigned,
  COALESCE(activity, 0)::bigint AS activity,
  COALESCE(balance, 0)::bigint AS balance
FROM rep.get_category_reports_gate(
  $1::uuid, 
  $2::date
)
ORDER BY category_name
`

type GetMonthCategoryReportsParams struct {
	BudgetID uuid.UUID
	MonthID  time.Time
}

type GetMonthCategoryReportsRow struct {
	Month        time.Time
	CategoryID   uuid.UUID
	CategoryName string
	Assigned     int64
	Activity     int64
	Balance      int64
}

func (q *Queries) GetMonthCategoryReports(ctx context.Context, arg GetMonthCategoryReportsParams) ([]GetMonthCategoryReportsRow, error) {
	rows, err := q.db.Query(ctx, getMonthCategoryReports, arg.BudgetID, arg.MonthID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthCategoryReportsRow
	for rows.Next() {
		var i GetMonthCategoryReportsRow
		if err := rows.Scan(
			&i.Month,
			&i.CategoryID,
			&i.CategoryName,
			&i.Assigned,
			&i.Activity,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthReport = `-- name: GetMonthReport :one
SELECT 
  month::DATE AS month,
  COALESCE(SUM(assigned), 0)::bigint AS assigned,
  COALESCE(SUM(activity), 0)::bigint AS activity,
  COALESCE(SUM(balance), 0)::bigint AS balance
FROM rep.get_category_reports_gate(
  $1::uuid, 
  $2::date
)
GROUP BY month
`

type GetMonthReportParams struct {
	BudgetID uuid.UUID
	MonthID  time.Time
}

type GetMonthReportRow struct {
	Month    time.Time
	Assigned int64
	Activity int64
	Balance  int64
}

func (q *Queries) GetMonthReport(ctx context.Context, arg GetMonthReportParams) (GetMonthReportRow, error) {
	row := q.db.QueryRow(ctx, getMonthReport, arg.BudgetID, arg.MonthID)
	var i GetMonthReportRow
	err := row.Scan(
		&i.Month,
		&i.Assigned,
		&i.Activity,
		&i.Balance,
	)
	return i, err
}
