// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE
FROM transactions
WHERE transactions.id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getTransactionByID = `-- name: GetTransactionByID :one
Select id, created_at, updated_at, budget_id, logger_id, account_id, transaction_date, payee_id, notes, cleared
FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.LoggerID,
		&i.AccountID,
		&i.TransactionDate,
		&i.PayeeID,
		&i.Notes,
		&i.Cleared,
	)
	return i, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT id, created_at, updated_at, budget_id, logger_id, account_id, transaction_date, payee_id, notes, cleared
FROM transactions
WHERE
    budget_id = $1
    AND ($2::uuid = '00000000-0000-0000-0000-000000000000' OR account_id = $2::uuid)
    AND (
        ($3::date = '0001-01-01' AND $4::date = '0001-01-01')
        OR
        (transaction_date >= $3::date AND transaction_date <= $4::date)
    )
ORDER BY transaction_date DESC
`

type GetTransactionsParams struct {
	BudgetID  uuid.UUID
	AccountID uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactions,
		arg.BudgetID,
		arg.AccountID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BudgetID,
			&i.LoggerID,
			&i.AccountID,
			&i.TransactionDate,
			&i.PayeeID,
			&i.Notes,
			&i.Cleared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsFromView = `-- name: GetTransactionsFromView :many
SELECT id, transaction_date, payee, notes, budget_id, account_id, logger_id, total_amount, categories
FROM transaction_view
WHERE
    budget_id = $1
    AND ($2::uuid IS NULL OR account_id = $2::uuid)
    AND ($3::date IS NULL OR transaction_date >= $3)
    AND ($4::date IS NULL OR transaction_date <= $4)
ORDER BY transaction_date DESC
`

type GetTransactionsFromViewParams struct {
	BudgetID  uuid.UUID
	AccountID uuid.UUID
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) GetTransactionsFromView(ctx context.Context, arg GetTransactionsFromViewParams) ([]TransactionView, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionsFromView,
		arg.BudgetID,
		arg.AccountID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionView
	for rows.Next() {
		var i TransactionView
		if err := rows.Scan(
			&i.ID,
			&i.TransactionDate,
			&i.Payee,
			&i.Notes,
			&i.BudgetID,
			&i.AccountID,
			&i.LoggerID,
			&i.TotalAmount,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logTransaction = `-- name: LogTransaction :one
INSERT INTO transactions (id, created_at, updated_at, budget_id, logger_id, account_id, transaction_date, payee_id, notes, cleared)
VALUES (
    gen_random_uuid(),
    DEFAULT,
    DEFAULT,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, created_at, updated_at, budget_id, logger_id, account_id, transaction_date, payee_id, notes, cleared
`

type LogTransactionParams struct {
	BudgetID        uuid.UUID
	LoggerID        uuid.UUID
	AccountID       uuid.UUID
	TransactionDate time.Time
	PayeeID         uuid.UUID
	Notes           string
	Cleared         bool
}

func (q *Queries) LogTransaction(ctx context.Context, arg LogTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, logTransaction,
		arg.BudgetID,
		arg.LoggerID,
		arg.AccountID,
		arg.TransactionDate,
		arg.PayeeID,
		arg.Notes,
		arg.Cleared,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.LoggerID,
		&i.AccountID,
		&i.TransactionDate,
		&i.PayeeID,
		&i.Notes,
		&i.Cleared,
	)
	return i, err
}
