// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE
FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getSplitsByTransactionID = `-- name: GetSplitsByTransactionID :many
SELECT id, transaction_id, category_id, amount
FROM transaction_splits
WHERE transaction_id = $1
`

func (q *Queries) GetSplitsByTransactionID(ctx context.Context, transactionID uuid.UUID) ([]TransactionSplit, error) {
	rows, err := q.db.QueryContext(ctx, getSplitsByTransactionID, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionSplit
	for rows.Next() {
		var i TransactionSplit
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.CategoryID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, created_at, updated_at, budget_id, logger_id, account_id, transaction_type, transaction_date, payee_id, notes, cleared
FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.LoggerID,
		&i.AccountID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.PayeeID,
		&i.Notes,
		&i.Cleared,
	)
	return i, err
}

const getTransactionDetails = `-- name: GetTransactionDetails :many
SELECT td.id, td.transaction_date, td.transaction_type, td.notes, payee, budget_name, account_name, logger_name, total_amount, splits, td.cleared, t.id, created_at, updated_at, budget_id, logger_id, account_id, t.transaction_type, t.transaction_date, payee_id, t.notes, t.cleared
FROM transaction_details td
JOIN transactions t ON td.id = t.id
WHERE
    t.budget_id = $1
    AND ($2::uuid = '00000000-0000-0000-0000-000000000000' OR t.account_id = $2::uuid)
    AND (
        $3::uuid = '00000000-0000-0000-0000-000000000000'
        OR EXISTS (
            SELECT 1
            FROM transaction_splits ts
            WHERE ts.transaction_id = t.id AND ts.category_id = $3::uuid
        )
    )
    AND ($4::uuid = '00000000-0000-0000-0000-000000000000' OR t.payee_id = $4::uuid)
    AND (
        ($5::date = '0001-01-01' AND $6::date = '0001-01-01')
        OR
        (t.transaction_date >= $5::date AND t.transaction_date <= $6::date)
    )
ORDER BY t.transaction_date DESC
`

type GetTransactionDetailsParams struct {
	BudgetID   uuid.UUID
	AccountID  uuid.UUID
	CategoryID uuid.UUID
	PayeeID    uuid.UUID
	StartDate  time.Time
	EndDate    time.Time
}

type GetTransactionDetailsRow struct {
	ID                uuid.UUID
	TransactionDate   time.Time
	TransactionType   string
	Notes             string
	Payee             string
	BudgetName        sql.NullString
	AccountName       sql.NullString
	LoggerName        sql.NullString
	TotalAmount       int64
	Splits            json.RawMessage
	Cleared           bool
	ID_2              uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	BudgetID          uuid.UUID
	LoggerID          uuid.UUID
	AccountID         uuid.UUID
	TransactionType_2 string
	TransactionDate_2 time.Time
	PayeeID           uuid.UUID
	Notes_2           string
	Cleared_2         bool
}

func (q *Queries) GetTransactionDetails(ctx context.Context, arg GetTransactionDetailsParams) ([]GetTransactionDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactionDetails,
		arg.BudgetID,
		arg.AccountID,
		arg.CategoryID,
		arg.PayeeID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionDetailsRow
	for rows.Next() {
		var i GetTransactionDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionDate,
			&i.TransactionType,
			&i.Notes,
			&i.Payee,
			&i.BudgetName,
			&i.AccountName,
			&i.LoggerName,
			&i.TotalAmount,
			&i.Splits,
			&i.Cleared,
			&i.ID_2,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BudgetID,
			&i.LoggerID,
			&i.AccountID,
			&i.TransactionType_2,
			&i.TransactionDate_2,
			&i.PayeeID,
			&i.Notes_2,
			&i.Cleared_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionDetailsByID = `-- name: GetTransactionDetailsByID :one
SELECT id, transaction_date, transaction_type, notes, payee, budget_name, account_name, logger_name, total_amount, splits, cleared
FROM transaction_details
WHERE id = $1
`

func (q *Queries) GetTransactionDetailsByID(ctx context.Context, id uuid.UUID) (TransactionDetail, error) {
	row := q.db.QueryRowContext(ctx, getTransactionDetailsByID, id)
	var i TransactionDetail
	err := row.Scan(
		&i.ID,
		&i.TransactionDate,
		&i.TransactionType,
		&i.Notes,
		&i.Payee,
		&i.BudgetName,
		&i.AccountName,
		&i.LoggerName,
		&i.TotalAmount,
		&i.Splits,
		&i.Cleared,
	)
	return i, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT id, created_at, updated_at, budget_id, logger_id, account_id, transaction_type, transaction_date, payee_id, notes, cleared
FROM transactions t
WHERE
    t.budget_id = $1
    AND ($2::uuid = '00000000-0000-0000-0000-000000000000' OR t.account_id = $2::uuid)
    AND (
        $3::uuid = '00000000-0000-0000-0000-000000000000'
        OR EXISTS (
            SELECT 1
            FROM transaction_splits ts
            WHERE ts.transaction_id = t.id AND ts.category_id = $3::uuid
        )
    )
    AND ($4::uuid = '00000000-0000-0000-0000-000000000000' OR t.payee_id = $4::uuid)
    AND (
        ($5::date = '0001-01-01' AND $6::date = '0001-01-01')
        OR
        (t.transaction_date >= $5::date AND t.transaction_date <= $6::date)
    )
ORDER BY t.transaction_date DESC
`

type GetTransactionsParams struct {
	BudgetID   uuid.UUID
	AccountID  uuid.UUID
	CategoryID uuid.UUID
	PayeeID    uuid.UUID
	StartDate  time.Time
	EndDate    time.Time
}

func (q *Queries) GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactions,
		arg.BudgetID,
		arg.AccountID,
		arg.CategoryID,
		arg.PayeeID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BudgetID,
			&i.LoggerID,
			&i.AccountID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.PayeeID,
			&i.Notes,
			&i.Cleared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logAccountTransfer = `-- name: LogAccountTransfer :one
INSERT INTO account_transfers (from_transaction_id, to_transaction_id)
VALUES (
    $1,
    $2
)
RETURNING from_transaction_id, to_transaction_id
`

type LogAccountTransferParams struct {
	FromTransactionID uuid.UUID
	ToTransactionID   uuid.UUID
}

func (q *Queries) LogAccountTransfer(ctx context.Context, arg LogAccountTransferParams) (AccountTransfer, error) {
	row := q.db.QueryRowContext(ctx, logAccountTransfer, arg.FromTransactionID, arg.ToTransactionID)
	var i AccountTransfer
	err := row.Scan(&i.FromTransactionID, &i.ToTransactionID)
	return i, err
}

const logTransaction = `-- name: LogTransaction :one
WITH
tr1 AS (
    INSERT INTO transactions (
        id, created_at, updated_at, budget_id, logger_id,
        account_id, transaction_type, transaction_date,
        payee_id, notes, cleared
    )
    VALUES (
        gen_random_uuid(),
        DEFAULT,
        DEFAULT,
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    )
    RETURNING id, created_at, updated_at, budget_id, logger_id, account_id, transaction_type, transaction_date, payee_id, notes, cleared
),
insert_splits AS (
    INSERT INTO transaction_splits (id, transaction_id, category_id, amount)
    SELECT
        gen_random_uuid(),
        tr1.id,
        CASE
            WHEN tr1.transaction_type ILIKE '%TRANSFER%' THEN NULL
            WHEN tr1.transaction_type ILIKE '%DEPOSIT%' AND key ILIKE '%UNCATEGORIZED%' THEN NULL
            ELSE key::uuid
        END,
        value::integer
    FROM tr1, json_each_text($9::json)
    RETURNING id, transaction_id, category_id, amount
)
SELECT 
    tr1.id, tr1.created_at, tr1.updated_at, tr1.budget_id, tr1.logger_id, tr1.account_id, tr1.transaction_type, tr1.transaction_date, tr1.payee_id, tr1.notes, tr1.cleared,
    (
        SELECT json_agg(insert_splits.*)
        FROM insert_splits
    ) AS splits
FROM tr1
`

type LogTransactionParams struct {
	BudgetID        uuid.UUID
	LoggerID        uuid.UUID
	AccountID       uuid.UUID
	TransactionType string
	TransactionDate time.Time
	PayeeID         uuid.UUID
	Notes           string
	Cleared         bool
	Amounts         json.RawMessage
}

type LogTransactionRow struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	BudgetID        uuid.UUID
	LoggerID        uuid.UUID
	AccountID       uuid.UUID
	TransactionType string
	TransactionDate time.Time
	PayeeID         uuid.UUID
	Notes           string
	Cleared         bool
	Splits          json.RawMessage
}

func (q *Queries) LogTransaction(ctx context.Context, arg LogTransactionParams) (LogTransactionRow, error) {
	row := q.db.QueryRowContext(ctx, logTransaction,
		arg.BudgetID,
		arg.LoggerID,
		arg.AccountID,
		arg.TransactionType,
		arg.TransactionDate,
		arg.PayeeID,
		arg.Notes,
		arg.Cleared,
		arg.Amounts,
	)
	var i LogTransactionRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.LoggerID,
		&i.AccountID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.PayeeID,
		&i.Notes,
		&i.Cleared,
		&i.Splits,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
WITH
updated_txn AS (
    UPDATE transactions t
    SET
        updated_at = NOW(),
        account_id = $1,
        transaction_type = $2,
        transaction_date = $3,
        payee_id = $4,
        notes = $5,
        cleared = $6
    WHERE t.id = $7
    RETURNING id, created_at, updated_at, budget_id, logger_id, account_id, transaction_type, transaction_date, payee_id, notes, cleared
),

deleted_splits AS (
    DELETE FROM transaction_splits
    WHERE transaction_id = $7
),

inserted_splits AS (
    INSERT INTO transaction_splits (id, transaction_id, category_id, amount)
    SELECT
        gen_random_uuid(),
        updated_txn.id,
        CASE
            WHEN updated_txn.transaction_type ILIKE '%TRANSFER%' THEN NULL
            WHEN updated_txn.transaction_type ILIKE '%DEPOSIT%' AND key ILIKE '%UNCATEGORIZED%' THEN NULL
            ELSE key::uuid
        END,
        value::integer
    FROM updated_txn, json_each_text($8::json)
    RETURNING id, transaction_id, category_id, amount
)
SELECT
    updated_txn.id, updated_txn.created_at, updated_txn.updated_at, updated_txn.budget_id, updated_txn.logger_id, updated_txn.account_id, updated_txn.transaction_type, updated_txn.transaction_date, updated_txn.payee_id, updated_txn.notes, updated_txn.cleared,
    (
        SELECT json_agg(inserted_splits.*)
        FROM inserted_splits
    ) AS splits
FROM updated_txn
`

type UpdateTransactionParams struct {
	AccountID       uuid.UUID
	TransactionType string
	TransactionDate time.Time
	PayeeID         uuid.UUID
	Notes           string
	Cleared         bool
	TransactionID   uuid.UUID
	Amounts         json.RawMessage
}

type UpdateTransactionRow struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	BudgetID        uuid.UUID
	LoggerID        uuid.UUID
	AccountID       uuid.UUID
	TransactionType string
	TransactionDate time.Time
	PayeeID         uuid.UUID
	Notes           string
	Cleared         bool
	Splits          json.RawMessage
}

// Clear out existing splits for this transaction
// Insert fresh splits from the provided JSON
func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (UpdateTransactionRow, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction,
		arg.AccountID,
		arg.TransactionType,
		arg.TransactionDate,
		arg.PayeeID,
		arg.Notes,
		arg.Cleared,
		arg.TransactionID,
		arg.Amounts,
	)
	var i UpdateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.LoggerID,
		&i.AccountID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.PayeeID,
		&i.Notes,
		&i.Cleared,
		&i.Splits,
	)
	return i, err
}
