// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE
FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const deleteTransactionSplits = `-- name: DeleteTransactionSplits :exec
  DELETE FROM transaction_splits
  WHERE transaction_id = $1
`

func (q *Queries) DeleteTransactionSplits(ctx context.Context, transactionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransactionSplits, transactionID)
	return err
}

const getLinkedTransaction = `-- name: GetLinkedTransaction :one
SELECT t.id, t.created_at, t.updated_at, t.budget_id, t.logger_id, t.account_id, t.transaction_type, t.transaction_date, t.payee_id, t.notes, t.cleared
FROM transactions t
JOIN account_transfers at
  ON (t.id = at.to_transaction_id AND at.from_transaction_id = $1)
     OR (t.id = at.from_transaction_id AND at.to_transaction_id = $1)
`

func (q *Queries) GetLinkedTransaction(ctx context.Context, fromTransactionID uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getLinkedTransaction, fromTransactionID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.LoggerID,
		&i.AccountID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.PayeeID,
		&i.Notes,
		&i.Cleared,
	)
	return i, err
}

const getSplitsByTransactionID = `-- name: GetSplitsByTransactionID :many
SELECT id, transaction_id, category_id, amount
FROM transaction_splits
WHERE transaction_id = $1
`

func (q *Queries) GetSplitsByTransactionID(ctx context.Context, transactionID uuid.UUID) ([]TransactionSplit, error) {
	rows, err := q.db.Query(ctx, getSplitsByTransactionID, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionSplit
	for rows.Next() {
		var i TransactionSplit
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.CategoryID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, created_at, updated_at, budget_id, logger_id, account_id, transaction_type, transaction_date, payee_id, notes, cleared
FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.LoggerID,
		&i.AccountID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.PayeeID,
		&i.Notes,
		&i.Cleared,
	)
	return i, err
}

const getTransactionDetails = `-- name: GetTransactionDetails :many

SELECT td.id, td.transaction_date, td.transaction_type, td.notes, td.payee_name, td.budget_name, td.account_name, td.logger_name, td.total_amount, td.splits, td.cleared
FROM transaction_details td
JOIN transactions t ON td.id = t.id
WHERE
  budget_id = $1::uuid
  AND (
      $2::uuid = '00000000-0000-0000-0000-000000000000'
      OR t.payee_id = $2::uuid
    )
  AND (
    $3::uuid = '00000000-0000-0000-0000-000000000000'
    OR t.payee_id = $3::uuid
  )
  AND (
    $4::uuid = '00000000-0000-0000-0000-000000000000'
    OR EXISTS (
      SELECT 1
      FROM transaction_splits ts
      WHERE ts.transaction_id = t.id AND ts.category_id = $4::uuid
    )
  )
  AND (
    ($5::date = '0001-01-01' AND $6::date = '0001-01-01')
    OR (t.transaction_date BETWEEN $5::date AND $6::date)
  )
ORDER BY t.transaction_date DESC
`

type GetTransactionDetailsParams struct {
	BudgetID   uuid.UUID
	AccountID  uuid.UUID
	PayeeID    uuid.UUID
	CategoryID uuid.UUID
	StartDate  time.Time
	EndDate    time.Time
}

// HACK:
// When it comes to nullable values, sqlc seems to have
// a difficult time inferring any sort of nullability
// on query parameters. This zero-value approach
// ensures that the zero-value UUIDs and timestamps
// passed to the query are properly compared.
func (q *Queries) GetTransactionDetails(ctx context.Context, arg GetTransactionDetailsParams) ([]TransactionDetail, error) {
	rows, err := q.db.Query(ctx, getTransactionDetails,
		arg.BudgetID,
		arg.AccountID,
		arg.PayeeID,
		arg.CategoryID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionDetail
	for rows.Next() {
		var i TransactionDetail
		if err := rows.Scan(
			&i.ID,
			&i.TransactionDate,
			&i.TransactionType,
			&i.Notes,
			&i.PayeeName,
			&i.BudgetName,
			&i.AccountName,
			&i.LoggerName,
			&i.TotalAmount,
			&i.Splits,
			&i.Cleared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionDetailsByID = `-- name: GetTransactionDetailsByID :one
SELECT id, transaction_date, transaction_type, notes, payee_name, budget_name, account_name, logger_name, total_amount, splits, cleared
FROM transaction_details
WHERE id = $1
`

func (q *Queries) GetTransactionDetailsByID(ctx context.Context, id uuid.UUID) (TransactionDetail, error) {
	row := q.db.QueryRow(ctx, getTransactionDetailsByID, id)
	var i TransactionDetail
	err := row.Scan(
		&i.ID,
		&i.TransactionDate,
		&i.TransactionType,
		&i.Notes,
		&i.PayeeName,
		&i.BudgetName,
		&i.AccountName,
		&i.LoggerName,
		&i.TotalAmount,
		&i.Splits,
		&i.Cleared,
	)
	return i, err
}

const getTransactions = `-- name: GetTransactions :many
SELECT t.id, t.created_at, t.updated_at, t.budget_id, t.logger_id, t.account_id, t.transaction_type, t.transaction_date, t.payee_id, t.notes, t.cleared
FROM transactions t
WHERE
  budget_id = $1::uuid
  AND (
      $2::uuid = '00000000-0000-0000-0000-000000000000'
      OR t.payee_id = $2::uuid
    )
  AND (
    $3::uuid = '00000000-0000-0000-0000-000000000000'
    OR t.payee_id = $3::uuid
  )
  AND (
    $4::uuid = '00000000-0000-0000-0000-000000000000'
    OR EXISTS (
      SELECT 1
      FROM transaction_splits ts
      WHERE ts.transaction_id = t.id AND ts.category_id = $4::uuid
    )
  )
  AND (
    ($5::date = '0001-01-01' AND $6::date = '0001-01-01')
    OR (t.transaction_date BETWEEN $5::date AND $6::date)
  )
ORDER BY t.transaction_date DESC
`

type GetTransactionsParams struct {
	BudgetID   uuid.UUID
	AccountID  uuid.UUID
	PayeeID    uuid.UUID
	CategoryID uuid.UUID
	StartDate  time.Time
	EndDate    time.Time
}

func (q *Queries) GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactions,
		arg.BudgetID,
		arg.AccountID,
		arg.PayeeID,
		arg.CategoryID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BudgetID,
			&i.LoggerID,
			&i.AccountID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.PayeeID,
			&i.Notes,
			&i.Cleared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logAccountTransfer = `-- name: LogAccountTransfer :one
INSERT INTO account_transfers (from_transaction_id, to_transaction_id)
VALUES (
    $1::uuid,
    $2::uuid
)
RETURNING from_transaction_id, to_transaction_id
`

type LogAccountTransferParams struct {
	FromTransactionID uuid.UUID
	ToTransactionID   uuid.UUID
}

func (q *Queries) LogAccountTransfer(ctx context.Context, arg LogAccountTransferParams) (AccountTransfer, error) {
	row := q.db.QueryRow(ctx, logAccountTransfer, arg.FromTransactionID, arg.ToTransactionID)
	var i AccountTransfer
	err := row.Scan(&i.FromTransactionID, &i.ToTransactionID)
	return i, err
}

const logTransaction = `-- name: LogTransaction :one
INSERT INTO transactions (
    id, created_at, updated_at, budget_id, logger_id,
    account_id, transaction_type, transaction_date,
    payee_id, notes, cleared)
VALUES (
    gen_random_uuid(),
    DEFAULT,
    DEFAULT,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, created_at, updated_at, budget_id, logger_id, account_id, transaction_type, transaction_date, payee_id, notes, cleared
`

type LogTransactionParams struct {
	BudgetID        uuid.UUID
	LoggerID        uuid.UUID
	AccountID       uuid.UUID
	TransactionType string
	TransactionDate time.Time
	PayeeID         uuid.UUID
	Notes           string
	Cleared         bool
}

func (q *Queries) LogTransaction(ctx context.Context, arg LogTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, logTransaction,
		arg.BudgetID,
		arg.LoggerID,
		arg.AccountID,
		arg.TransactionType,
		arg.TransactionDate,
		arg.PayeeID,
		arg.Notes,
		arg.Cleared,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BudgetID,
		&i.LoggerID,
		&i.AccountID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.PayeeID,
		&i.Notes,
		&i.Cleared,
	)
	return i, err
}

const logTransactionSplits = `-- name: LogTransactionSplits :many
INSERT INTO transaction_splits (id, transaction_id, category_id, amount)
SELECT
  gen_random_uuid(),
  $1::uuid,
  CASE
    WHEN t.transaction_type ILIKE '%TRANSFER%' THEN NULL
    WHEN t.transaction_type ILIKE '%DEPOSIT%' AND key ILIKE '%UNCATEGORIZED%' THEN NULL
    ELSE key::uuid
  END,
  value::integer
FROM json_each_text($2::json)
JOIN transactions t ON t.id = $1::uuid
RETURNING id, transaction_id, category_id, amount
`

type LogTransactionSplitsParams struct {
	TransactionID uuid.UUID
	Amounts       []byte
}

func (q *Queries) LogTransactionSplits(ctx context.Context, arg LogTransactionSplitsParams) ([]TransactionSplit, error) {
	rows, err := q.db.Query(ctx, logTransactionSplits, arg.TransactionID, arg.Amounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionSplit
	for rows.Next() {
		var i TransactionSplit
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.CategoryID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions t
SET
  updated_at = NOW(),
  account_id = $1,
  transaction_type = $2,
  transaction_date = $3,
  payee_id = $4,
  notes = $5,
  cleared = $6
WHERE t.id = $7
`

type UpdateTransactionParams struct {
	AccountID       uuid.UUID
	TransactionType string
	TransactionDate time.Time
	PayeeID         uuid.UUID
	Notes           string
	Cleared         bool
	TransactionID   uuid.UUID
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.Exec(ctx, updateTransaction,
		arg.AccountID,
		arg.TransactionType,
		arg.TransactionDate,
		arg.PayeeID,
		arg.Notes,
		arg.Cleared,
		arg.TransactionID,
	)
	return err
}
