#!/bin/bash
#Should fail to assign category to group after group has been deleted.
source ./functions

reset 
heading "CREATING user_1...."
USER1=$(create_user "user_1" "123456")
heading "LOGGING IN user_1...."
JWT_USER1=$(login "user_1" "123456")
heading "CREATING Subscriptions GROUP UNDER user_1...."
GROUP1=$(create_group "$JWT_USER1" "$USER1" "Subscriptions" "For tracking expenses related to subscription services.")
heading "CREATING Webflyx CATEGORY UNDER user_1...."
CATEGORY1=$(create_category "$JWT_USER1" "$USER1" "" "Webflyx" "Webflyx subscription")
heading "DELETING Subscriptions GROUP UNDER user_1...."
delete_user_group "$JWT_USER1" "$USER1" "$GROUP1"
heading "ASSIGNING Webflyx CATEGORY UNDER user_1 TO Subscriptions GROUP...."
assign_cat_to_grp "$JWT_USER1" "$USER1" "$CATEGORY1" "$GROUP1"
