#!/bin/bash
#Should create two groups. Then those groups should both be deleted after all is said and done, and getting them should then return null.
source ./functions

reset 
heading "CREATING AND LOGGING IN user_1 AND user_2...."
USER1=$(create_user "user_1" "123456")
echo $USER1
USER2=$(create_user "user_2" "654321")
echo $USER2
JWT_USER1=$(login "user_1" "123456")
echo $JWT_USER1
JWT_USER2=$(login "user_2" "654321")
echo $JWT_USER2
heading "CREATING BUDGETS FOR user_1 AND user_2...."
BUDGET1=$(create_budget "$JWT_USER1" "User1 Personal" "For personal finance")
echo $BUDGET1
BUDGET2=$(create_budget "$JWT_USER2" "User2 Personal" "For personal finance")
echo $BUDGET2
heading "CREATING GROUPS FOR BUDGET1 AND BUDGET2...."
GROUP1=$(create_group "$JWT_USER1" "$BUDGET1" "Home Goods" "I always use an after shave lotion with little or no alcohol, because alcohol dries your face out and makes you look older.")
echo $GROUP1
GROUP2=$(create_group "$JWT_USER2" "$BUDGET2" "Living Expenses" "This is a free country...it's not a rent-free country.")
echo $GROUP2
heading "GETTING GROUPS FROM BUDGET1 AND BUDGET2...."
get_budget_groups "$JWT_USER1" "$BUDGET1"
get_budget_groups "$JWT_USER2" "$BUDGET2"
heading "DELETING GROUPS from BUDGET1 AND BUDGET2...."
delete_budget_group "$JWT_USER1" "$BUDGET1" "$GROUP1"
delete_budget_group "$JWT_USER2" "$BUDGET2" "$GROUP2"
heading "GETTING GROUPS FROM BUDGET1 AND BUDGET2 (AGAIN)...."
get_budget_groups "$JWT_USER1" "$BUDGET1"
get_budget_groups "$JWT_USER2" "$BUDGET2"
