#!/bin/bash
#Should fail to assign category to group after group has been deleted.
source ./functions

reset 
heading "CREATING user_1...."
USER1=$(create_user "user_1" "123456")
heading "LOGGING IN user_1...."
JWT_USER1=$(login "user_1" "123456")
heading "CREATING BUDGET: Personal FOR user_1...."
BUDGET1=$(create_budget "$JWT_USER1" "Personal" "For personal finance")
echo $BUDGET1
heading "CREATING Subscriptions GROUP UNDER user_1...."
GROUP1=$(create_group "$JWT_USER1" "$BUDGET1" "Subscriptions" "For tracking expenses related to subscription services.")
echo $GROUP1
heading "CREATING Webflyx CATEGORY UNDER user_1...."
CATEGORY1=$(create_category "$JWT_USER1" "$BUDGET1" "" "Webflyx" "Webflyx subscription")
echo $CATEGORY1
heading "DELETING Subscriptions GROUP UNDER user_1 Personal budget...."
delete_budget_group "$JWT_USER1" "$BUDGET1" "$GROUP1"
heading "ASSIGNING Webflyx CATEGORY UNDER BUDGET: Personal TO Subscriptions GROUP...."
assign_cat_to_grp "$JWT_USER1" "$BUDGET1" "$CATEGORY1" "$GROUP1"
