#!/bin/bash
#Should return null, as no categories were assigned to the group.
source ./functions

reset 
heading "CREATING user_1..."
USER1=$(create_user "user_1" "123456")
echo $USER1
heading "LOGGING IN user_!...."
JWT_USER1=$(login "user_1" "123456")
echo $JWT_USER1
heading "CREATING BUDGET UNDER user_1...."
BUDGET1=$(create_budget "$JWT_USER1" "Personal" "For personal finance")
heading "CREATING Subscriptions GROUP UNDER BUDGET1...."
GROUP1=$(create_group "$JWT_USER1" "$BUDGET1" "Subscriptions" "For tracking subscription services and their associated fees.")
echo $GROUP1
heading "CREATING A CATEGORY WITHOUT ASSIGNING A GROUP...."
CATEGORY1=$(create_category "$JWT_USER1" "$BUDGET1" "" "Sciencemail Subs." "Homelabbing email can be a pain; I prefer to pay a company somewhere else to host my email privately. This budget category tracks my membership spending for their service.")
heading "GETTING CATEGORIES UNDER user_1 Subscriptions GROUP...."
get_budget_categories "$JWT_USER1" "$BUDGET1" "?group_id$GROUP1"
