#!/bin/bash
#Creates a budget with an admin user, and adds other users. Along the way, various roles attempt various actions that they should or should not be able to do; authorizations that should be verified.
source ./functions

heading "DELETING EXISTING USERS FROM THE DATABASE...."
reset
heading "CREATING & LOGGING IN 4 USERS...."
USER1=$(create_user "u1" "pass1")
echo $USER1
JWT_USER1=$(login "u1" "pass1")
echo $JWT_USER1
USER2=$(create_user "u2" "pass2")
echo $USER2
JWT_USER2=$(login "u2" "pass2")
echo $JWT_USER2
USER3=$(create_user "u3" "pass3")
echo $USER3
JWT_USER3=$(login "u3" "pass3")
echo $JWT_USER3
USER4=$(create_user "u4" "pass4")
echo $USER4
JWT_USER4=$(login "u4" "pass4")
echo $JWT_USER4
heading "CREATING BUDGET WITH u1 AS ADMIN: 'Webflyx Org'"
BUDGET1=$(create_budget "$JWT_USER1" "Webflyx Org" "To track expenses within the Webflyx Organization.")
echo $BUDGET1
heading "CREATING BUDGET WITH u1 AS ADMIN: 'U1 Personal'"
BUDGET2=$(create_budget "$JWT_USER1" "Personal" "U1's personal finance budgeting.")
echo $BUDGET2
heading "TEST(WANT 1): Try adding u2 as ADMIN using u4 (not in budget), then as MANAGER. Both should fail."
assign_member_to_budget "$JWT_USER4" "$BUDGET1" "$USER2" "$ADMIN"
assign_member_to_budget "$JWT_USER4" "$BUDGET1" "$USER2" "$MANAGER"
heading "TEST(WANT 0): Add u4 to Webflyx Org as admin u1, with role: VIEWER."
assign_member_to_budget "$JWT_USER1" "$BUDGET1" "$USER4" "VIEWER"
heading "TEST(WANT 1 OBJ): Get u4 budgets"
get_user_budgets "$JWT_USER4" ""
heading "TEST(WANT 1): Attempt to add u2 as MANAGER using u4. Should fail auth check."
assign_member_to_budget "$JWT_USER4" "$BUDGET1" "$USER2" "MANAGER"
heading "As u1, add u2 and u3 as MANAGER and CONTRIBUTOR, respectively."
assign_member_to_budget "$JWT_USER1" "$BUDGET1" "$USER2" "MANAGER"
assign_member_to_budget "$JWT_USER1" "$BUDGET1" "$USER3" "CONTRIBUTOR"
heading "TEST(WANT 1): Attempting deletion of Webflyx Org budget as u2. Should fail; only admin can do it."
delete_user_budget "$JWT_USER2" "$BUDGET1"
heading "Test(WANT 1): Attempting revocation of u3 using u4. Should fail."
revoke_budget_membership "$JWT_USER4" "$BUDGET1" "$USER3"
heading "Test(WANT 0): Attempting revocation of u3 using u1. Should succeed."
revoke_budget_membership "$JWT_USER1" "$BUDGET1" "$USER3"
heading "TEST(WANT 2 OBJ): Get u1 budgets (webflyx & personal)"
get_user_budgets "$JWT_USER1" ""
heading "TEST(WANT 1): Attempting deletion of Webflyx Org budget as u1. Should succeed."
delete_user_budget "$JWT_USER1" "$BUDGET1"
heading "TEST(WANT 1 OBJ): Get u1 budgets (personal is what's left)"
get_user_budgets "$JWT_USER1" ""
heading "TEST(WANT 0 OBJ): Get u4 budgets (none left)"
get_user_budgets "$JWT_USER4" ""