#!/bin/bash
#Should show two users created, logged in, and creating groups with various categories. Under user_2, one category is made without an assigned group, and later assigned to a group. After getting categories from under that group the 2nd time, this category should be seen under the group.
source ./functions

reset 
heading "CREATING user_1 AND user_2...."
USER1=$(create_user "user_1" "123456")
echo $USER1
USER2=$(create_user "user_2" "654321")
echo $USER2
heading "LOGGING IN user_1 AND user_2...."
JWT_USER1=$(login "user_1" "123456")
echo $JWT_USER1
JWT_USER2=$(login "user_2" "654321")
echo $JWT_USER2
heading "CREATING BUDGETS FOR user_1 AND user_2...."
BUDGET1=$(create_budget "$JWT_USER1" "User1 Personal" "For personal finance")
echo $BUDGET1
BUDGET2=$(create_budget "$JWT_USER2" "User2 Personal" "For personal finance")
echo $BUDGET2
heading "CREATING GROUPS FOR user_1 AND user_2...."
GROUP1=$(create_group "$JWT_USER1" "$BUDGET1" "SAVINGS" "Holds categories related to saving money for one or more purposes.")
GROUP2=$(create_group "$JWT_USER2" "$BUDGET2" "SPENDING" "Holds categories related to elective monthly spending")
GROUP3=$(create_group "$JWT_USER2" "$BUDGET2" "SUBSCRIPTIONS" "For tracking subscription service fees")
heading "CREATING CATEGORIES FOR user_1 AND user_2...."
CATEGORY1=$(create_category "$JWT_USER1" "$BUDGET1" "$GROUP1" "Tattoo Fund" "Saving up for new tattoos!")
echo $CATEGORY1
CATEGORY2=$(create_category "$JWT_USER1" "$BUDGET1" "$GROUP1" "Main Savings" "A penny saved is a penny earned.")
echo $CATEGORY2
CATEGORY3=$(create_category "$JWT_USER1" "$BUDGET1" "$GROUP1" "Investment Buffer" "Holds money to be invested later when it reaches Index Fund minimums, and/or when the market dips.")
echo $CATEGORY3
CATEGORY4=$(create_category "$JWT_USER2" "$BUDGET2" "$GROUP2" "Dining Out" "For fine dining, fast food, and everything in-between!")
echo $CATEGORY4
CATEGORY5=$(create_category "$JWT_USER2" "$BUDGET2" "$GROUP2" "Treats" "A budget category for tracking how much I spend on sweet treats.")
echo $CATEGORY5
CATEGORY6=$(create_category "$JWT_USER2" "$BUDGET2" "$GROUP2" "Home Goods" "Shampoo, dish soap, paper towels...etc.")
echo $CATEGORY6
CATEGORY7=$(create_category "$JWT_USER2" "$BUDGET2" "$GROUP3" "Bigstore Club Membership" "A budget dedicated to tracking annual fees for my membership with Bigstore, where I buy most of my groceries.")
echo $CATEGORY7
CATEGORY8=$(create_category "$JWT_USER2" "$BUDGET2" "" "Sciencemail Subs." "Homelabbing email can be a pain; I prefer to pay a company somewhere else to host my email privately. This budget category tracks my membership spending for their service.")
echo $CATEGORY8
heading "GETTING BUDGET GROUPS FOR user_1...."
get_budget_groups "$JWT_USER1" "$BUDGET1" ""
heading "GETTING BUDGET GROUPS FOR user_2...."
get_budget_groups "$JWT_USER2" "$BUDGET2" ""
heading "GETTING CATEGORIES OF BUDGET1...."
get_budget_categories "$JWT_USER1" "$BUDGET1" ""
heading "GETTING CATEGORIES OF BUDGET2...."
get_budget_categories "$JWT_USER2" "$BUDGET2" ""
heading "GETTING CATEGORIES OF BUDGET2 GROUP: 'SPENDING'"
get_budget_categories "$JWT_USER2" "$BUDGET2" "?group_id=$GROUP2"
heading "GETTING CATEGORIES FROM BUDGET2 GROUP: 'SUBSCRIPTIONS'"
get_budget_categories "$JWT_USER2" "$BUDGET2" "?group_id=$GROUP3"
heading "ASSIGNING BUDGET2 CATEGORY: 'Sciencemail Subs.' TO user_2 GROUP: 'SUBSCRIPTIONS'"
assign_cat_to_grp "$JWT_USER2" "$BUDGET2" "$CATEGORY8" "$GROUP3"
heading "GETTING CATEGORIES FROM BUDGET2 GROUP: 'SUBSCRIPTIONS' (AGAIN)"
get_budget_categories "$JWT_USER2" "$BUDGET2" "?group_id=$GROUP3"
